### ISSUE TITLE
[Bug report] metanode panic

### ISSUE THREAD

**Issue by zcola** [chubaofs/chubaofs#651]
**Describe the bug**
```
panic: interface conversion: btree.Item is nil, not *metanode.Inode

goroutine 360 [running]:
github.com/chubaofs/chubaofs/metanode.(*metaPartition).deleteMarkedInodes(0xc004a72000, 0xc005082c88, 0x4, 0x64)
        /go/src/github.com/chubaofs/chubaofs/metanode/partition_free_list.go:131 +0x5b1
github.com/chubaofs/chubaofs/metanode.(*metaPartition).deleteWorker(0xc004a72000)
        /go/src/github.com/chubaofs/chubaofs/metanode/partition_free_list.go:115 +0x20f
created by github.com/chubaofs/chubaofs/metanode.(*metaPartition).startFreeList
        /go/src/github.com/chubaofs/chubaofs/metanode/partition_free_list.go:47 +0x129
```
**Environment**
Describe your server system version, kernel version

ChubaoFS Server
Branch:
Commit:
Build: go1.12.6 linux amd64 2020-05-12 10:27

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by awzhgw** [comment]
@zcola  it has fix it on
